/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'mobile' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'addedAt' : bigint,
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
}
export interface SignupEntry {
  'id' : bigint,
  'city' : string,
  'fullName' : string,
  'email' : string,
  'timestamp' : bigint,
  'mobile' : string,
}
export interface UserProfile {
  'city' : string,
  'name' : string,
  'email' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, Array<string>, boolean, boolean, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSignups' : ActorMethod<[], Array<SignupEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getRecentProducts' : ActorMethod<[], Array<Product>>,
  'getSignupsByCity' : ActorMethod<[string], Array<SignupEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmin' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markProductAsFeatured' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setStock' : ActorMethod<[bigint, boolean, bigint], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'submitSignup' : ActorMethod<[string, string, string, string], bigint>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      Array<string>,
      boolean,
      boolean,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];